//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HSEntities : DbContext
    {
        public HSEntities()
            : base("name=HSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ChiTietVP> tb_ChiTietVP { get; set; }
        public virtual DbSet<tb_ChucVu> tb_ChucVu { get; set; }
        public virtual DbSet<tb_DanhMucLoi> tb_DanhMucLoi { get; set; }
        public virtual DbSet<tb_DanToc> tb_DanToc { get; set; }
        public virtual DbSet<tb_GiaoVien> tb_GiaoVien { get; set; }
        public virtual DbSet<tb_GiaoVien_Lop> tb_GiaoVien_Lop { get; set; }
        public virtual DbSet<tb_HocKy> tb_HocKy { get; set; }
        public virtual DbSet<tb_HocSinh> tb_HocSinh { get; set; }
        public virtual DbSet<tb_HS_Lop_NamHoc> tb_HS_Lop_NamHoc { get; set; }
        public virtual DbSet<tb_KhoiLop> tb_KhoiLop { get; set; }
        public virtual DbSet<tb_Lop> tb_Lop { get; set; }
        public virtual DbSet<tb_MonHoc> tb_MonHoc { get; set; }
        public virtual DbSet<tb_NamHoc> tb_NamHoc { get; set; }
        public virtual DbSet<tb_TonGiao> tb_TonGiao { get; set; }
        public virtual DbSet<tb_TrinhDo> tb_TrinhDo { get; set; }
        public virtual DbSet<tb_Truong> tb_Truong { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<tb_ViPham> tb_ViPham { get; set; }
    
        public virtual ObjectResult<THONGKE_VIPAHM_NAMHOC_Result> THONGKE_VIPAHM_NAMHOC(Nullable<int> mANH)
        {
            var mANHParameter = mANH.HasValue ?
                new ObjectParameter("MANH", mANH) :
                new ObjectParameter("MANH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONGKE_VIPAHM_NAMHOC_Result>("THONGKE_VIPAHM_NAMHOC", mANHParameter);
        }
    }
}
