//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GiaoVien_Lop
    {
        public int MAGV_LOP { get; set; }
        public Nullable<int> MAGV { get; set; }
        public Nullable<int> MALOP { get; set; }
        public Nullable<int> MANH { get; set; }
        public Nullable<int> MAHK { get; set; }
    
        public virtual tb_GiaoVien tb_GiaoVien { get; set; }
        public virtual tb_Lop tb_Lop { get; set; }
        public virtual tb_NamHoc tb_NamHoc { get; set; }
        public virtual tb_HocKy tb_HocKy { get; set; }
    }
}
