CREATE PROC THONGKE_VIPAHM_NAMHOC ( @MANH int )
AS
	BEGIN
		SELECT A.MANH, D.TENNH, C.TENLOP, E.MAKHOI, E.TENKHOI, SUM(B.DIEM) AS DIEM
		FROM tb_ViPham A, tb_ChiTietVP B, tb_Lop C, tb_NamHoc D, tb_KhoiLop E
		WHERE A.MAVP = B.MAVP AND A.MANH = D.MANH AND A.MALOP = C.MALOP AND E.MAKHOI = C.MAKHOI AND A.MANH = @MANH
		GROUP BY A.MANH, E.MAKHOI, E.TENKHOI, D.TENNH, A.MALOP, C.TENLOP
	END

